//------------------------------------------------------------------------------
// <auto-generated>
//     此程式碼是由工具產生
//     如果重新產生程式碼，將會遺失此檔案的變更。
// </auto-generated>
//------------------------------------------------------------------------------
namespace Models.Event
{
	using Models;
	using System;
	using System.Collections.Generic;
	using System.Linq;
	using System.Text;

	/// <summary>
	/// 案件查詢參數
	/// </summary>
	public class EventSetParam : PageParam
	{
		/// <summary>
		/// 院區
		/// </summary>
		public virtual int Location
		{
			get;
			set;
		}

		/// <summary>
		/// 區域
		/// </summary>
		public virtual int Area
		{
			get;
			set;
		}

		/// <summary>
		/// 案件類別
		/// </summary>
		public virtual byte EventType
		{
			get;
			set;
		}

		/// <summary>
		/// 案件狀態
		/// </summary>
		public virtual byte EventStatus
		{
			get;
			set;
		}

		/// <summary>
		/// 關鍵查詢
		/// </summary>
		public virtual string Keyword
		{
			get;
			set;
		}

	}
}

