//------------------------------------------------------------------------------
// <auto-generated>
//     此程式碼是由工具產生
//     如果重新產生程式碼，將會遺失此檔案的變更。
// </auto-generated>
//------------------------------------------------------------------------------
namespace Models.Event
{
	using Models.Tree;
	using System;
	using System.Collections.Generic;
	using System.Linq;
	using System.Text;

	/// <summary>
	/// 代辦案件集合
	/// </summary>
	public class EventSetsViewModel
	{
		/// <summary>
		/// 代辦案件集合
		/// </summary>
		public virtual IEnumerable<EventSetViewModel> EventSets
		{
			get;
			set;
		}

		/// <summary>
		/// 每頁數量
		/// </summary>
		public virtual decimal PagedItems
		{
			get;
			set;
		}

	}
}

