//------------------------------------------------------------------------------
// <auto-generated>
//     此程式碼是由工具產生
//     如果重新產生程式碼，將會遺失此檔案的變更。
// </auto-generated>
//------------------------------------------------------------------------------
namespace Models.Event
{
	using System;
	using System.Collections.Generic;
	using System.Linq;
	using System.Text;

	public enum EventStatusEnum : int
	{
		/// <summary>
		/// 處理中
		/// </summary>
		Processing = 2,
		/// <summary>
		/// 待處理
		/// </summary>
		Pending = 1,
		/// <summary>
		/// 已完成
		/// </summary>
		Completed = 3,
		/// <summary>
		/// 已逾時
		/// </summary>
		Timed = 4,
		/// <summary>
		/// 已結案
		/// </summary>
		Closed = 9,
	}
}
