//------------------------------------------------------------------------------
// <auto-generated>
//     此程式碼是由工具產生
//     如果重新產生程式碼，將會遺失此檔案的變更。
// </auto-generated>
//------------------------------------------------------------------------------
namespace Models.Event
{
	using Entities;
	using System;
	using System.Collections.Generic;
	using System.Linq;
	using System.Text;

	/// <summary>
	/// 代辦案件-下拉選單
	/// </summary>
	public class EventSelect
	{
		/// <summary>
		/// 院區集合
		/// </summary>
		public virtual IEnumerable<Groups> Locations
		{
			get;
			set;
		}

		/// <summary>
		/// 區域集合
		/// </summary>
		public virtual IEnumerable<Groups> Areas
		{
			get;
			set;
		}

		/// <summary>
		/// 案件類別集合
		/// </summary>
		public virtual IEnumerable<OptionSets> EventTypes
		{
			get;
			set;
		}

		/// <summary>
		/// 案件狀態集合
		/// </summary>
		public virtual IEnumerable<OptionSets> EventStatuses
		{
			get;
			set;
		}

	}
}

