//------------------------------------------------------------------------------
// <auto-generated>
//     此程式碼是由工具產生
//     如果重新產生程式碼，將會遺失此檔案的變更。
// </auto-generated>
//------------------------------------------------------------------------------
namespace Models.Event
{
	using Entities;
	using System;
	using System.Collections.Generic;
	using System.Linq;
	using System.Text;

	/// <summary>
	/// 代辦案件 ViewModel
	/// </summary>
	public class EventSetViewModel
	{
		/// <summary>
		/// 案件類別
		/// </summary>
		public virtual string EventTypeName
		{
			get;
			set;
		}

		/// <summary>
		/// 案件狀態名稱
		/// </summary>
		public virtual string EventSatausName
		{
			get;
			set;
		}

		/// <summary>
		/// 院區名稱名稱
		/// </summary>
		public virtual string LocationName
		{
			get;
			set;
		}

		/// <summary>
		/// 區域名稱
		/// </summary>
		public virtual string AreaName
		{
			get;
			set;
		}

		/// <summary>
		/// 植栽資料
		/// </summary>
		public virtual TreeItems Item
		{
			get;
			set;
		}

		/// <summary>
		/// 代辦案件資料
		/// </summary>
		public virtual EventSets EventSet
		{
			get;
			set;
		}

		/// <summary>
		/// 代辦案件-成案
		/// </summary>
		public virtual bool IsAssign
		{
			get;
			set;
		}

	}
}

