//------------------------------------------------------------------------------
// <auto-generated>
//     此程式碼是由工具產生
//     如果重新產生程式碼，將會遺失此檔案的變更。
// </auto-generated>
//------------------------------------------------------------------------------
namespace Models.Tree
{
	using Entities;
	using System;
	using System.Collections.Generic;
	using System.Linq;
	using System.Text;

	public class AddSelect
	{
		/// <summary>
		/// 植栽分類
		/// </summary>
		public virtual IEnumerable<OptionSets> TreeClass
		{
			get;
			set;
		}

		/// <summary>
		/// 植栽樹種
		/// </summary>
		public virtual IEnumerable<OptionSets> TreeTypes
		{
			get;
			set;
		}

		/// <summary>
		/// 院區集合
		/// </summary>
		public virtual IEnumerable<Groups> Locations
		{
			get;
			set;
		}

		/// <summary>
		/// 區域集合
		/// </summary>
		public virtual IEnumerable<Groups> Areas
		{
			get;
			set;
		}

		/// <summary>
		/// 健康度集合
		/// </summary>
		public virtual IEnumerable<OptionSets> Healths
		{
			get;
			set;
		}

		/// <summary>
		/// 來源集合
		/// </summary>
		public virtual IEnumerable<OptionSets> Origins
		{
			get;
			set;
		}

	}
}

