//------------------------------------------------------------------------------
// <auto-generated>
//     此程式碼是由工具產生
//     如果重新產生程式碼，將會遺失此檔案的變更。
// </auto-generated>
//------------------------------------------------------------------------------
namespace Models.Tree
{
	using Entities;
	using System;
	using System.Collections.Generic;
	using System.Linq;
	using System.Text;

	public class ItemSelect
	{
		/// <summary>
		/// 區域集合
		/// </summary>
		public virtual IEnumerable<Groups> Areas
		{
			get;
			set;
		}

		/// <summary>
		/// 搜尋條件
		/// </summary>
		public virtual IEnumerable<OptionSets> ItemCondition
		{
			get;
			set;
		}

		/// <summary>
		/// 院區集合
		/// </summary>
		public virtual IEnumerable<Groups> Locations
		{
			get;
			set;
		}

		/// <summary>
		/// 搜尋自串
		/// </summary>
		public virtual string Condition
		{
			get;
			set;
		}

	}
}

