//------------------------------------------------------------------------------
// <auto-generated>
//     此程式碼是由工具產生
//     如果重新產生程式碼，將會遺失此檔案的變更。
// </auto-generated>
//------------------------------------------------------------------------------
namespace Models.Tree
{
	using Entities;
	using System;
	using System.Collections.Generic;
	using System.Linq;
	using System.Text;

	public class TreeItemViewModel
	{
		public virtual TreeItems Item
		{
			get;
			set;
		}

		public virtual List<iTree.DataBase::Entities::TreeImages> Images
		{
			get;
			set;
		}

	}
}

