//------------------------------------------------------------------------------
// <auto-generated>
//     此程式碼是由工具產生
//     如果重新產生程式碼，將會遺失此檔案的變更。
// </auto-generated>
//------------------------------------------------------------------------------
namespace iTree.DataBas.Repositories
{
	using System;
	using System.Collections.Generic;
	using System.Linq;
	using System.Text;

	public class TreeRepository
	{
		public virtual void GetTreeItems(TreeItemParam param)
		{
			throw new System.NotImplementedException();
		}

	}
}

