//------------------------------------------------------------------------------
// <auto-generated>
//     此程式碼是由工具產生
//     如果重新產生程式碼，將會遺失此檔案的變更。
// </auto-generated>
//------------------------------------------------------------------------------
using Models.Tree;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

public class TreeRepository
{
	public virtual ItemSelect GetItemSelect(TreeItemParam parm)
	{
		throw new System.NotImplementedException();
	}

	/// <summary>
	/// 查詢植栽基本集合
	/// </summary>
	public virtual TreeItemsViewModel GetTreeItems(TreeItemParam param)
	{
		throw new System.NotImplementedException();
	}

	public virtual AddSelect GetAddSelect()
	{
		throw new System.NotImplementedException();
	}

	public virtual void SetTreeItem(TreeItemViewModel vm)
	{
		throw new System.NotImplementedException();
	}

}

